### ISSUE TITLE
Valine 评论无法加载、发送

### ISSUE THREAD

**Issue by bianyukun1213** [looooading/looooading.github.io#1]
控制台看，报 CORS 错误。是不是跟[安全域名](https://valine.js.org/quickstart.html#%E5%AE%89%E5%85%A8%E5%9F%9F%E5%90%8D)配置有关？

**Comment by looooading** [comment]
收到，正在配置、学习

**Comment by looooading** [comment]
> 控制台看，报 CORS 错误。是不是跟[安全域名](https://valine.js.org/quickstart.html#%E5%AE%89%E5%85%A8%E5%9F%9F%E5%90%8D)配置有关？

应该已经可以了，我试了一下，能用了
